<script src="<?php echo JS?>/jquery-3.2.1.min.js"></script>
<script src="<?php echo JS?>/bootstrap.min.js"></script>
<script src="<?php echo JS?>/chosen.proto.min.js"></script>
<script src="<?php echo JS?>/chosen.jquery.min.js"></script>
<script src="<?php echo JS?>/bootstrapValidator.min.js"></script>
<script src="<?php echo JS?>/main.js"></script>
<script>
  $('.chosen-select').chosen();
</script>
</body>
</html>