<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="<?php echo CSS ?>/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo CSS ?>/prism.css">
    <link rel="stylesheet" href="<?php echo CSS ?>/chosen.min.css">
    <link rel="stylesheet" href="<?php echo CSS ?>/bootstrapValidator.min.css">
    <link rel="stylesheet" href="<?php echo CSS ?>/main.css">
</head>
<body>